### ISSUE TITLE
MiniSelect V2 gcode commands not working?

### ISSUE THREAD

**Issue by martzcodes** [nokemono42/MP-Select-Mini-Web#12]
I just gave this a go on my MiniSelect V2 (I'm a noob at this) and the gcode commands don't seem to do anything.  With my extruder centered home doesn't do anything, listing SD card contents do anything, and my file uploads (~2MB) get stuck at 7%.

Am I missing something?

**Comment by Bubba2017** [comment]
I too had the same problem.  Try reloading the defaults by sending (substitute you own IP address)
http://192.168.1.107/set?code=M502
http://192.168.1.107/set?code=M501

This worked for me.  You should see a web page that simply says "OK"  if you don't, they didn't work.  After that the web interface worked for me.  However I still can't see the list of files on the SD card.  but everything else seems to work as far as control.

**Comment by junkjunker** [comment]
Using the V2, I'm having the same issue as @Bubba2017 that the "M20 ; List SD card files" does not work.  Clicking the refresh button doesn't seem to do anything.  Any thoughts on how to make this work?  Thanks!
![image](https://user-images.githubusercontent.com/25068787/44949316-39e50e80-adec-11e8-9663-d7fc7f6b4301.png)

**Comment by junkjunker** [comment]
p.s.  LOVE this project as a way to get a usable webGUI for the MP Select Mini printers!  Thanks!

**Comment by nokemono42** [comment]
@junkjunker I don't have a V2 so trying to trouble will be tricky.

Can you check your browser console for javascript errors? And either screenshot or copy and paste any errors.

Firefox: Tools->Web Developer->Web Console
Chrome: View->Developer->Java Script Console

**Comment by screwyluie** [comment]
doesn't work on my min v2 either. only error I see is: 

`[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.`

**Comment by screwyluie** [comment]
removing

`        <script type="text/javascript">
            function startup() {
                if ($("#stat").text() != 'Printing') {
                    sendCmd('M563 S5', 'Enable faster Wi-Fi file uploads');
                }
            }
        </script>`

from the webui.html fixes it.

**Comment by screwyluie** [comment]
after much testing everything seems to work if you use M563 S4 instead. The only exception is the SD card contents which will list only 2 files instead of everything on the card. no idea why.

**Comment by nokemono42** [comment]
@screwyluie Not sure what the Chrome error is about. I will try using Chrome more and see what happens.

S5 or S4 are just speed variations. Different firmware versions seem to freak out at the higher speeds. I know the Delta Mini suffers from the same problem. You can adjust the speed in the webui.html to what works best. That is why I moved that piece of code out of the linked JS files.

Also, I noticed that sometimes the file listing does get messed up. I think the output gets grabbled at times. Since the source code isn't available I have to pinpoint when it does stupid things and write code around it.

**Comment by nokemono42** [comment]
Closing issue. Reports are that V2 printers should use 'M563 S4' instead. I am also making the file listing more robust in hopes to squash some bugs. New version coming soon.
