### ISSUE TITLE
TRASH button doesn't always work - instead it refreshed the sd-card

### ISSUE THREAD

**Issue by supak111** [nokemono42/MP-Select-Mini-Web#13]
Trash button doesn't alway work to delete files from sd-card.  Usually only the very top trash button works and deletes the top file.  But if I click the top button again or any other trash button it doesn't delete but it actually REFRESHES the sd-card.  Almost like the buttons become mixed up.

**Comment by nokemono42** [comment]
@supak111 Can you provide the console output for when this happens? There is no real API for the printer so everything is done with string interpretation. Maybe there is an unexpected character that needs a work around.
![screen shot 2018-05-02 at 9 07 22 am](https://user-images.githubusercontent.com/1263913/39524944-9f73145e-4de8-11e8-93f5-bf23213ac01e.png)

**Comment by supak111** [comment]
Just tried it again and seems to work fine.  This was fresh after starting the printer.  

When I had the issue I think it was after doing a few prints and not hard restarting the printer.  As soon as I see it happen again I will report when and what I was doing.


<img width="433" alt="2018-05-02 at 11 56 32 am" src="https://user-images.githubusercontent.com/6550667/39537746-1bf429b6-4e00-11e8-9eff-fae8d58e9dbd.png">

**Comment by supak111** [comment]
I think I figured out which files can NOT be deleted though web ui with trash buttons.  Anything with an extra period in the name wont delete.

**Comment by nokemono42** [comment]
@supak111 Interesting. Let me see if I can make a work around for that.

**Comment by nokemono42** [comment]
Closing this. Reference #14 as the issues are related to periods in the filename. Fix coming.
