### ISSUE TITLE
UI requires an active internet connection.

### ISSUE THREAD

**Issue by veive** [nokemono42/MP-Select-Mini-Web#3]
Pretty much exactly what it says on the tin. this makes calls to cloudflare. You cannot run it on an isolated network or if your internet is down.

**Comment by nokemono42** [comment]
@veive I was wondering about that. I thought it would be too nerdy to make a version people could use on an isolated network.

Originally Maylan had just stuff all the needed CSS and JS into the single webui.html file. While this project is adding a lot more features I don't think its a big enough page to tax the built in web server. I'll work on that.

**Comment by veive** [comment]
Too nerdy? No such thing.

For what it's worth I routinely expect my printer to handle gcode files on
excess of 10 to 15 meg. I don't think expecting it to blind fire a single
html file with some CSS and JavaScript that the browser has to deal with
should be a big deal. I get that storage is a finite resource but I doubt
you will break a MB of HTML, JavaScript, and CSS. If we cannot rely on the
board to serve that to a single client how the heck will it handle ten
times that in gcode that it actually needs to process?

On Feb 25, 2017 7:30 PM, "Joey" <notifications@github.com> wrote:

@veive <https://github.com/veive> I was wondering about that. I thought it
would be too nerdy to make a version people could use on an isolated
network.

Originally Maylan had just stuff all the needed CSS and JS into the single
webui.html file. While this project is adding a lot more features I don't
think its a big enough page to tax the built in web server. I'll work on
that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nokemono42/MP-Select-Mini-Web/issues/3#issuecomment-282525500>,
or mute the thread

**Comment by nokemono42** [comment]
I'm almost ready to do a release what doesn't require an internet connection, but I need to find a work around for the icons. They are currently loaded as a font. I need to find some SVG code to replace them with or redraw them. I'll probably just redraw them, it's only 4 icons.

**Comment by douglsmith** [comment]
Here is an archive of the Font Awesome icons as SVG.
https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/white/svg

**Comment by nokemono42** [comment]
The master branch is now the upgraded Web UI with offline support. Give it a try and share your feedback.
