### ISSUE TITLE
Recommend change to G28 code for all axes

### ISSUE THREAD

**Issue by Leemonoid** [nokemono42/MP-Select-Mini-Web#4]
In Alpha 0.67 you send a **G28** code to home all the axes, which for some reason makes my printer jump into print mode as if a print job started.

Sending the code as **G28 X0 Y0 Z0** homes the printer but does not make the user interface change into printing mode. 

Recommend changing the code in webui_js to fix this problem.

**Comment by nokemono42** [comment]
That was fixed, but there might have been an issues with Github syncing the change. If the change still isn't showing then try emptying your browser cache.

**Comment by Leemonoid** [comment]
I can confirm that it works properly now.  Thank you!
