### ISSUE TITLE
speed up Wi-Fi uploading button

### ISSUE THREAD

**Issue by douglsmith** [nokemono42/MP-Select-Mini-Web#5]
How about a button that sends the Wi-Fi speed up g-code so we don't have to remember what it is? Or would it work to just automatically send it on page load?

**Comment by RDiazPR** [comment]
I submitted my branch, I just added this "Activate fast transfer button", and a "Purge" button.

**Comment by douglsmith** [comment]
Cool, thanks!

I was going to test it but I don't see a pull request here.

**Comment by nokemono42** [comment]
@douglsmith The "web-ui-update" branch is a beta UI update that I am working on. It runs the Fast Wifi gCode on each refresh for convenience.

**Comment by RDiazPR** [comment]
whoa, very nice. Looks great, and it loads a lot faster. You should update the screenshot on this branch, it still shows the previous version. Great work!

**Comment by nokemono42** [comment]
The master branch is now the upgraded Web UI. Give it a try and share your feedback.

**Comment by nokemono42** [comment]
The master branch is now the upgraded Web UI. Give it a try and share your feedback.

**Comment by douglsmith** [comment]
That's fantastic. Thanks!
